[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
grow_space = "7KvbAAK7kP72zcdC24vDn9L51TDV8v9he4hNJ3S7ZU51"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://xolana.xen.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
